[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cb_kafka_consumer"
version = "0.1.5"
authors = [
    { name = "Mehdi Bakhtiari", email = "mehdone@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'kafka-python ~= 2.0.2',
    'python-snappy ~= 0.6.1',
    'crc32c ~= 2.3',
]

#[project.urls]
#"Homepage" = "https://github.com/pypa/sampleproject"
#"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"
