[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "useless_crawler"
version = "0.0.4"
authors = [
  { name="Barry Melton", email="barry@sureisfun.com" },
]
description = "A simple crawler that acts as the backbone for other operations"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[tool.hatch.build.targets.wheel]
include = ["main.py"]


dependencies = [
  "beautifulsoup4>=4.11.1",
  "bs4>=0.0.0",
  "certifi>=2022.12.7",
  "cffi>=1.15.1",
  "charset-normalizer>=3.0.1",
  "cryptography>=39.0.1",
  "idna>=3.4",
  "lxml>=4.9.2",
  "markdownify>=0.11.6",
  "mysqlclient>=2.1.1",
  "nanoid>=2.0.0",
  "pycparser>=2.21",
  "PyMySQL>=1.0.2",
  "python-dotenv>=0.21.1",
  "requests>=2.28.2",
  "six>=1.16.0",
  "soupsieve>=2.4",
  "SQLAlchemy>=2.0.4",
  "typing_extensions>=4.5.0",
  "urllib3>=1.26.14",
]


[project.urls]
"Homepage" = "https://github.com/bmelton/python-crawler"
"Bug Tracker" = "https://github.com/bmelton/python-crawler/issues"