[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "launchflow"
version = "0.0.2"
authors = [
    { name = "Caleb Van Dyke", email = "caleb@launchflow.com" },
    { name = "Josh Tanke", email = "josh@launchflow.com" },
]
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "google-auth",
    "pydata-google-auth",
    "pyaml",
    "typer[all]",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "flake8",
    "setuptools",
    "wheel"
]

[project.scripts]
launch = "launch.cli:main"

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters
