[project]
name = "rtm_fast_unification"
version = "0.0.1"
authors = [
  { name="Animesh", email="author@example.com" },
]
description = "A fast unification ds code package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "astroid",
    "asttokens",
    "autopep8",
    "backcall",
    "certifi",
    "charset-normalizer",
    "colorama",
    "debugpy",
    "decorator",
    "dill",
    "entrypoints",
    "et-xmlfile",
    "executing",
    "idna",
    "ipykernel",
    "ipython",
    "isort",
    "jedi",
    "joblib",
    "jupyter-client",
    "jupyter-core",
    "lazy-object-proxy",
    "matplotlib-inline",
    "mccabe",
    "nest-asyncio",
    "numpy",
    "openpyxl",
    "packaging",
    "pandas",
    "parso",
    "patsy",
    "pickleshare",
    "platformdirs",
    "prompt-toolkit",
    "psutil",
    "pure-eval",
    "pycodestyle",
    "Pygments",
    "pylint",
    "pyparsing",
    "python-dateutil",
    "pytz",
    "pywin32",
    "pyzmq",
    "requests",
    "scikit-learn",
    "scipy",
    "six",
    "sklearn",
    "stack-data",
    "statsmodels",
    "threadpoolctl",
    "tomli",
    "tomlkit",
    "tornado",
    "traitlets",
    "typing-extensions",
    "urllib3",
    "wcwidth",
    "wrapt"
]


[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"