version: '3.7'

services:
  jupyter-local:
    image: '${HMD_CONTAINER_REGISTRY:-ghcr.io/neuronsphere}/hmd-img-jupyter-server:${HMD_IMG_JUPYTER_SERVER_VERSION:-stable}'
    container_name: jupyter-local
    user: root
    ports:
      - '8888:8888'
    env_file:
      - '${HMD_HOME}/.config/hmd.env'
    environment:
      HMD_DATA: /hmd/data/
      HMD_HOME: /home/jovyan/hmd
      HMD_REPO_NAME: hmd-img-jupyter-server
      HMD_REPO_VERSION: ${HMD_IMG_JUPYTER_SERVER_VERSION:-stable}
      HMD_INSTANCE_NAME: local
      HMD_TRANSFORM_DIAGRAM_PATH: /hmd/data/diagrams/transform
      PIP_EXTRA_INDEX_URL: ${PIP_EXTRA_INDEX_URL}
      NB_USER: ${UID}
    labels:
      io.hmdlabs.service: local_hmd-img-jupyter-server
      io.hmdlabs.environment: local_local_hmd
      io.hmdlabs.version: local_aaa
    volumes:
      - type: bind
        source: ${HMD_HOME}/.config
        target: /home/jovyan/hmd/.config
      - type: bind
        source: ${HMD_HOME}/.cache
        target: /home/jovyan/hmd/.cache
      - type: bind
        source: ${HMD_HOME}/data
        target: /hmd/data/
      - type: bind
        source: ${HMD_HOME}/language_packs/
        target: /hmd/schemas/
      - type: bind
        source: ${HMD_PROJECTS_PATH}
        target: /home/jovyan/work
