[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "datahub_py"
version = "0.0.15"
authors = [
  { name="Julien L", email="julien@leap-forward.ca" },
]
description = "Datahub core"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'Flask==2.2.2',
    'Flask-RESTful==0.3.9',
    'pika==1.3.1',
    'requests==2.28.1',
    'setuptools==67.4.0',
    'tinydb==4.7.1',
    'tqdm==4.64.1',
    'Werkzeug==2.2.3',
]

[project.urls]
"Homepage" = "https://github.com/26medias/Datahub-py"
"Bug Tracker" = "https://github.com/26medias/Datahub-py/issues"