[tool.poetry]
name = "pytelligence"
version = "0.2.1"
description = "pycaret clone aimed for simplicity and production ready code"
authors = ["Friedrich G. Froebel <froebel.business@gmail.com>"]
license = "All rights reserved"

[tool.poetry.dependencies]
python = "^3.9"
scikit-learn = "^1.1.1"
pandas = "^1.4.3"
seaborn = "^0.11.2"
PyYAML = "^6.0"
optuna = "^2.10.1"
plotly = "^5.10.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-watch = "^4.2.0"
notebook = "^6.4.12"
black = {extras = ["jupyter"], version = "^22.6.0"}
isort = "^5.10.1"
pyarrow = "^8.0.0"
colorlog = "^6.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black" 